#regla: para generar "ejecutable" uso "main.c", lo que está debajo es el comando (siempre con un tab)
ejecutable: main.c
	gcc main.c -o ejecutable

#regla clean, no tiene dependencias, borra el ejecutable
clean: 
	rm ejecutable

